name: IrisCore
version: 0.0.2
description: Core Plugin of Kova
author: Zevyx
api-version: 1.19
main: de.zevyx.iriscore.IrisCore
commands:
  iris:
  gamemode:
    aliases:
      - gm
  world:
    aliases:
      - w
  heal:
  invsee:
  enderchest:
    aliases:
      - ec
  addenchantment: